// 2.3 - When can you first sell shares in a company?

const afterItHasOperated = 'After is has operated.';
const fromSecondStockRound = 'From the second stock round onwards.';
const asSoonAsYouLike = 'As soon as you like.';
const notVoluntary = 'You may not voluntarily sell them until it has operated. You may be forced to sell them earlier in an emergency money-raising step.';
const style1846 = 'For the President, as soon as you like. For other shareholders, after it has operated.';
const style1860 = 'As soon as you like, but shares in companies with no trains are sold at half the current market price.';

export default {
  '1761': afterItHasOperated,
  '1812': afterItHasOperated,
  '1817': afterItHasOperated,
  '1822': afterItHasOperated,
  '1822CA': afterItHasOperated,
  '1824': afterItHasOperated,
  '1826': afterItHasOperated,
  '1827Jr': afterItHasOperated,
  '1837': afterItHasOperated,
  '1837SX': afterItHasOperated,
  '1838 Rheinland': afterItHasOperated,
  '1847': afterItHasOperated,
  '1847AE': afterItHasOperated,
  '1851': afterItHasOperated,
  '1853': afterItHasOperated,
  '1858': afterItHasOperated,
  '1861': afterItHasOperated,
  '1865 Sardinia': afterItHasOperated,
  '1867': afterItHasOperated,
  '1893': afterItHasOperated,
  '1895': afterItHasOperated,
  '1898': afterItHasOperated,
  '18Ardennes': afterItHasOperated,
  '18BL': afterItHasOperated,
  '18Dixie': afterItHasOperated,
  '18EU': afterItHasOperated,
  '18FL': afterItHasOperated,
  '18GL': afterItHasOperated,
  '18Neb': afterItHasOperated,
  '18NW': afterItHasOperated,
  '18Rhl': afterItHasOperated,
  '18Ruhr': afterItHasOperated,
  '18Scan': afterItHasOperated,
  '18US': afterItHasOperated,
  '18USA': afterItHasOperated,
  '18VA': afterItHasOperated,
  'Steam Over Holland': afterItHasOperated,
  '1800': fromSecondStockRound,
  '1825': fromSecondStockRound,
  '1829': fromSecondStockRound,
  '1829 Mainline': fromSecondStockRound,
  '1830': fromSecondStockRound,
  '1830BC': fromSecondStockRound,
  '1832': fromSecondStockRound,
  '1834': fromSecondStockRound,
  '1848': fromSecondStockRound,
  '1850': fromSecondStockRound,
  '1857': fromSecondStockRound,
  '1859': fromSecondStockRound,
  '1862': fromSecondStockRound,
  '1868': fromSecondStockRound,
  '1869 The Golden Spike': fromSecondStockRound,
  '1869 USA West': fromSecondStockRound,
  '1870': fromSecondStockRound,
  '1879': fromSecondStockRound,
  '1880': fromSecondStockRound,
  '1881': fromSecondStockRound,
  '1889': fromSecondStockRound,
  '1891': fromSecondStockRound,
  '18??': fromSecondStockRound,
  '18Africa': fromSecondStockRound,
  '18C2C': fromSecondStockRound,
  '18CZ': fromSecondStockRound,
  '18EC': fromSecondStockRound,
  '18EZ Level 2': fromSecondStockRound,
  '18EZ Level 3': fromSecondStockRound,
  '18GA': fromSecondStockRound,
  '18GM': fromSecondStockRound,
  '18Kaas': fromSecondStockRound,
  '18Mex': fromSecondStockRound,
  '18MS': fromSecondStockRound,
  '18MW': fromSecondStockRound,
  '18NK': fromSecondStockRound,
  '18NL': fromSecondStockRound,
  '18PA': fromSecondStockRound,
  '18SA': fromSecondStockRound,
  '18SS': fromSecondStockRound,
  '18SY': fromSecondStockRound,
  '18TN': fromSecondStockRound,
  'Crisis': fromSecondStockRound,
  '1830 Cardgame': 'Not applicable. Shares may not be sold at any time.',
  '1831': asSoonAsYouLike,
  '18CLE': asSoonAsYouLike,
  'Poseidon': asSoonAsYouLike,
  'Railroad Barons': asSoonAsYouLike,
  'Rolling Stock': asSoonAsYouLike,
  '1841': notVoluntary,
  '1849': notVoluntary,
  '1835': 'After it has operated; except that you may sell Prussian shares once they have floated.',
  '1844': 'In the second SR. But if it has not yet operated, you receive the price it is at after moving down.',
  '1846': style1846,
  '2038': style1846,
  '1854': "As soon as the Director's certificate has been bought (but not in the first SR).",
  // Question 1856: Are share sales allowed in the first stock round?
  '1856': "As soon as you like; but you may not sell a share in the same share turn in which you bought it, though you may sell other identical ones. (The rules say 'certificate', but author Bill Dixon explains that 'share' is meant.)",
  '1860': style1860,
  '18GB': style1860,
  '1862EA': 'In any Stock round, but you may only sell shares you owned prior to that round.',
  '1873': 'From the second stock round onwards, but if it has not yet operated, you receive the next lower share price (despite not actually lowering the share price in that situation).',
  '18EZ Level 1': 'Not Applicable (no share dealing).',
  '18Ireland': 'From the second regular stock round onwards. Note that the initial stock round is followed by the first regular stock round.',
  '18NY': 'After it has operated; except that you may sell NYC shares may be sold the stock round after it is formed even if it has not operated.',
  '18OE': 'After Train Phase 1. Shares of regional companies may never be sold.',
  '18West': 'After it has operated, but the UP is considered to have operated prior to the start of the game and may be sold in the first stock round.',
  '1842': 'TODO',
};
