// 1.2 - Does the price of a private company drop by 5 for no sale in the first round?

const no = 'No.';
const yes = 'Yes, first private only.';
const removedFromGame = 'No. If no private companies are purchased they are all removed from the game.';
const forcedOnFirstPlayer = 'No. First player must buy the first private if round passes out.';
const notApplicable = 'Not applicable.';
const yesForAll = 'Yes, for all private companies. Any private company price may drop to zero as a result of this.';
const flAndUs = 'No. Privates are bought at face value, following a bidding process to determine the order in which players make their purchases. 18US has Concessions instead of Privates.';

export default {
  '1761': no,
  '1800': yes,
  '1812': 'No. If none of the initial set of Private Companies are put up for auction, a new random set of Private Companies are chosen and the game starts again.',
  '1817': removedFromGame,
  '1822': no,
  '1822CA': no,
  '1824': no,
  '1825': 'No. One private per player dealt at random and sold compulsorily. With more than 4 players, the others get LNWR shares.',
  '1826': forcedOnFirstPlayer,
  '1827Jr': yes,
  '1829 Mainline': 'Not applicable - initial share holdings are dealt, not sold.',
  '1829': yes,
  '1830 Cardgame': notApplicable,
  '1830BC': yes,
  '1830NL': 'Yes, but the second company, not the first, which pays no dividend.',
  '1830': `v1 & v3: ${yes}, v2: ${no}`,
  '1831': notApplicable,
  '1832': yes,
  '1834': yes,
  '1835': no,
  '1837': '10 subtracted.',
  '1837SX': no,
  '1838 Rheinland': no,
  '1841': notApplicable,
  '1842': 'Not stated.',
  '1844': yes,
  '1846': 'No. Players draw from a mixed deck of private companies and dummy cards, choosing which items to keep. The last drawn private company may be passed round the table, reducing in price by $10  each time it is passed on, until it is either bought, or taken at no cost.',
  '1847': no,
  '1847AE': no,
  '1848': no,
  '1849': `v1 & v3: ${notApplicable}, v4: ${yes}`,
  '1850': yes,
  '1851': 'No. One private per player is dealt at random and sold compulsorily.',
  '1853': notApplicable,
  '1854': yes,
  '1856': yes,
  '1857': 'TODO',
  '1858': no,
  '1859': 'TODO',
  '1860': 'No. All auctions start at zero.',
  '1861': yesForAll,
  '1862': yes,
  '1862EA': notApplicable,
  '1865 Sardinia': notApplicable,
  '1867': yesForAll,
  '1868': yes,
  '1869 The Golden Spike': yes,
  '1869 USA West': 'No. The price for all unsold privates drops by 10 if a stock round ends with one or more privates unsold. In the second stock round, if nobody buys the first private, the first player must buy it for 1.',
  '1870': yes,
  '1873': 'Not applicable. But after the initial auction, a Dutch auction commences with 10 subtracted whenever all players pass.',
  '1879': notApplicable,
  '1880': no,
  '1881': notApplicable,
  '1889': 'Yes, Takamatsu ER(A) only. Must buy if 0 Yen.',
  '1891': yes,
  '1893': 'No, but any starting package certificates unsold after the first round are offered for sale in the next SR. If nobody wants the offered certificate, its price is reduced by 10 until the offered price is 50% (rounded up) of the initial price. If nobody wants it at that price, the player offering it has to buy it, or if they do not have enough cash, the player to their right. This procedure is repeated for the remaining starting package certificates.',
  '1895': yes,
  '1898': notApplicable,
  '18??': 'No. Any set of private companies not bid on when all players pass is removed from the game.',
  '18Africa': no,
  '18Ardennes': notApplicable,
  '18BL': yes,
  '18C2C': 'Yes, but after an operating round. May apply to the Great River Shipping Company and/or the Schuykill Valley Railroad.',
  '18CLE': yes,
  '18CZ': no,
  '18Dixie': no,
  '18EC': yes,
  '18EU': notApplicable,
  '18EZ Level 1': notApplicable,
  '18EZ Level 2': notApplicable,
  '18EZ Level 3': yes,
  '18FL': flAndUs,
  '18GA': yes,
  '18GB': 'No. If any privates are not sold when all players pass, those with bids a re sold and the unsold privates are redcued in price by 10.',
  '18GL': 'No. If all players pass without buying the first private, the player with the priority must buy it for its face value.',
  '18GM': yes,
  '18Ireland': yes,
  '18Kaas': yes,
  '18MS': no,
  '18MW': 'No. There are in effect seven simultaneous auctions for the privates.',
  '18Mex': yes,
  '18NK': yes,
  '18NL': 'Yes, for the first two privates only.',
  '18NW': forcedOnFirstPlayer,
  '18NY': yes,
  '18Neb': 'No. If all palyers pass consecutively during the first stock round, the face value for any items without bids is reduced by 10. This may happen more than once.',
  '18OE': 'Yes. If all players pass before the entire opening packet has been sold, all items on the topmost row are reduced by 5.',
  '18PA': no,
  '18Rhl': yes,
  '18Ruhr': no,
  '18SA': 'No. If all players pass before all private companies are sold, the unsold private companies are removed from the game.',
  '18SS': yes,
  '18SY': yes,
  '18Scan': no,
  '18TN': yes,
  '18US': flAndUs,
  '18USA': removedFromGame,
  '18VA': 'No. A series of auction is undertaken. Any private that has not been bid on at the end of each auction is reduced in price by 10.',
  '18West': notApplicable,
  '2038': no,
  'Crisis': notApplicable,
  'Poseidon': no,
  'Railroad Barons': no,
  'Rolling Stock': notApplicable,
  'Steam Over Holland': 'No. A number of privates equal to the number of players are selected at random and auctioned in sequence. If nobody bids the private is removed from the game.',
};
