// 2.10 - Can companies buy shares?

const theirOwnInORsAndSell = 'Their own, in ORs. They can also sell, but cannot buy and sell in the same turn.';
const style1861 = "Privates, in ORs, once a 3 train has been sold, and their own from the bank pool, by 'redemption', in ORs.";
const style1817 = 'Their own, in SRs, when the president chooses to act on behalf of the company instead of for himself.';
const no = 'No.';
const theirOwnInORs = 'Their own, in ORs.';
const privatesAfter3Train = 'Privates, in ORs, once a 3 train has been sold.';
const style1847 = 'Quarries, in ORs, once a 4 train has been sold.';
const yesButNotTheirOwn = 'Yes, but not their own.';
const theirOwnInSRs = 'Their own, in SRs.';

export default {
  '1761': 'Privates and minor companies in ORs, once a 3 train has been sold, for 1 to face value.',
  '1800': theirOwnInORsAndSell,
  '18GL': theirOwnInORsAndSell,
  '18Ireland': theirOwnInORsAndSell,
  '1812': style1861,
  '1861': style1861,
  '1867': style1861,
  '1817': style1817,
  '18USA': style1817,
  '1822': 'Yes. From phases 2, 3 or 5 (depending on which private company is under consideration), major and minor companies may take private companies from a consenting player. Not all private companies may be taken by minor companies. No compensation is paid to the player. Major companies may also acquire minor companies, and may issue stock from their treasury to the bank pool.',
  '1822CA': 'Yes. From phases 1, 2, 3 or 5 (depending on which private company is under consideration), major and minor companies may take private companies from a consenting player. Not all private companies may be taken by minor companies. No compensation is paid to the player. Major companies may also acquire minor companies, and may issue stock from their treasury to the bank pool.',
  '1824': 'Private companies may only be bought by the H or R companies.',
  '1825': no,
  '1827Jr': no,
  '1829': no,
  '1829 Mainline': no,
  '1830 Cardgame': no,
  '1835': no,
  '1837': no,
  '1853': no,
  '1854': no,
  '1860': no,
  '1869 USA West': no,
  '1873': no,
  '1879': no,
  '1880': no,
  '1893': no,
  '1895': no,
  '18Ardennes': no,
  '18BL': no,
  '18Dixie': no,
  '18EC': no,
  '18EZ Level 2': no,
  '18FL': no,
  '18GB': no,
  '18MS': no,
  '18Neb': no,
  '18NL': no,
  '18Rhl': no,
  '18Scan': no,
  '18SY': `Generalisation: ${privatesAfter3Train}, Original: ${no}`,
  '18VA': no,
  'Poseidon': no,
  'Rolling Stock': no,
  '1826': theirOwnInORs,
  '18EU': theirOwnInORs,
  '1830': privatesAfter3Train,
  '1830BC': privatesAfter3Train,
  '1834': privatesAfter3Train,
  '1838 Rheinland': privatesAfter3Train,
  '1844': privatesAfter3Train,
  '1848': privatesAfter3Train,
  '1856': privatesAfter3Train,
  '1857': privatesAfter3Train,
  '1859': privatesAfter3Train,
  '1868': privatesAfter3Train,
  '1889': privatesAfter3Train,
  '1891': privatesAfter3Train,
  '18CLE': privatesAfter3Train,
  '18EZ Level 3': privatesAfter3Train,
  '18GA': privatesAfter3Train,
  '18GM': privatesAfter3Train,
  '18Kaas': privatesAfter3Train,
  '18Mex': privatesAfter3Train,
  '18SS': privatesAfter3Train,
  '1831': 'Yes, in SRs, limit of 25% of own common stock. May buy up to limit immediately after any share is sold into bank pool.',
  '1832': "Their own, by 'redemption', in SRs. Also privates, in ORs, once a 3 train has been sold. The West Virginia Coal Fields can be bought in phase two for half to full face value. The London Investment Company, the Central Rail Road and Canal Company and the Southern Bank (if in play) may not be bought by companies.",
  '1837SX': 'Yes, one of their own from the bank pool, which is then placed in the initial offering. They may alternatively sell one of their own shares from the initial offering to the bank pool.',
  '1841': 'Yes, up to five certificates, but not their own; in ORs.',
  '1842': 'Only in the HAV.',
  '1846': 'Their own; in ORs. Privates, in ORs, in Phases I and II.',
  '1847': `Basic Game: ${no}, Expert Game: ${style1847}`,
  '1847AE': 'Quarries, in ORs, once a 4 train has been sold.',
  '1849': 'Their own; in ORs.',
  '1850': "Their own, by 'redemption', in SRs. Also privates, in ORs, once a 3 train has been sold. The Mississippi River Bridge Company and the Mesabi Mining Company can be bought in phase two for half to full face value.",
  '1851': 'Their own, in ORs. But they may not own more than 50% of themselves.',
  '1858': 'Their own, as the last action when operating. May also issue shares from their second operating turn on.',
  '1862': "Their own, by 'redemption', in ORs.",
  '1862EA': "Their own, by 'redemption', in ORs. They may also be required to sell shares to raise funds for forced train purchases.",
  '1865 Sardinia': 'No, but companies may be given Maritime Companies (privates) and may absorb other companies.',
  '1869 The Golden Spike': 'First private only, for half to twice face value.',
  '1870': "Their own, by 'redemption', in SRs. Also privates, in ORs, once a 3 train has been sold, for half to double face value. The Mississippi River Bridge Company can be bought by the MP or the SSW in phase one for half to full face value.",
  '1881': 'Yes, tramway companies may buy and sell S-Bahn certificates.',
  '1898': 'Yes, up to five certificates, but not their own; in ORs; or they may buy back per turn one of their own from the bank pool to their initial offering.',
  '18??': "Their own, by 'redemption', in SRs. Also privates, in ORs, before the purchase of the first '3' train for one half of face value, and once a 3 train has been sold for one half to double face value.",
  '18Africa': yesButNotTheirOwn,
  'Crisis': yesButNotTheirOwn,
  '18C2C': "Their own, by 'redemption', in SRs. Also privates, in ORs, once a 3 train has been sold.",
  '18CZ': 'Companies may acquire smaller companies.',
  '18EZ Level 1': 'Not Applicable (no share dealing).',
  '18MW': theirOwnInSRs,
  '18NY': theirOwnInSRs,
  '18NK': "Their own, by 'redemption', in SRs. Also privates, in ORs, once a 3 train has been sold.",
  '18NW': 'Their own, in ORs, but not in their first operating turn. They can also sell, but cannot buy and sell in the same turn.',
  '18OE': 'Major company may buy their own, in ORs. They can also sell, but cannot buy and sell in the same turn. They may also buy one abandoned minor company per OR from the bank pool.',
  '18PA': 'Companies may acquire local companies.',
  '18Ruhr': 'Their own, in ORs. They may buy or sell a single share, which moves between the bank pool and the initial offering or vice versa. If a share is sold the company gains the current price and the price will fall by one row.',
  '18SA': 'Their own, from the bank pool, in ORs. But they may not own more than 10% of themselves.',
  '18TN': 'Privates, in ORs, once a 3 train has been sold. May also buy one private at face value in the first OR of the game.',
  '18US': 'Western Concessions once the Western Railroad Convention has taken place, except for the Denver and Rio Grande and the Pacific Railway Act.',
  '18West': 'Yes, Granger Road companies in a Merger and Acquisition round.',
  '2038': 'Privates, in ORs, once phase II has started.',
  'Railroad Barons': 'Yes, Holdings may buy Railroad Corporations (equivalent to trains in most 18xx games).',
  'Steam Over Holland': 'Yes, their own from the bank pool during ORs. Also privates, in ORs, once a 3 train has been sold.',
};
