// 4.2 - If you sell shares so that their tokens end up in one stack, what order are they stacked in?

const onTheBottom = 'New arrivals are placed below existing tokens.';
const unspecified = 'Unspecified.';
const notApplicable = 'Not applicable.';

export default {
  '1761': onTheBottom,
  '1812': onTheBottom,
  '1817': onTheBottom,
  '1822': onTheBottom,
  '1822CA': onTheBottom,
  '1824': onTheBottom,
  '1826': onTheBottom,
  '1830': `v1: ${unspecified}, v2 & v3: ${onTheBottom}`,
  '1831': onTheBottom,
  '1832': onTheBottom,
  '1837SX': onTheBottom,
  '1847AE': onTheBottom,
  '1850': onTheBottom,
  '1858': onTheBottom,
  '1860': onTheBottom,
  '1861': onTheBottom,
  '1862EA': onTheBottom,
  '1865 Sardinia': onTheBottom,
  '1867': onTheBottom,
  '1869 The Golden Spike': onTheBottom,
  '1869 USA West': onTheBottom,
  '1873': onTheBottom,
  '1881': onTheBottom,
  '1889': onTheBottom,
  '1893': onTheBottom,
  '18Africa': onTheBottom,
  '18Ardennes': onTheBottom,
  '18BL': onTheBottom,
  '18CZ': onTheBottom,
  '18Dixie': onTheBottom,
  '18EC': onTheBottom,
  '18EZ Level 2': onTheBottom,
  '18EZ Level 3': onTheBottom,
  '18FL': onTheBottom,
  '18GA': onTheBottom,
  '18GB': onTheBottom,
  '18GL': onTheBottom,
  '18GM': onTheBottom,
  '18Ireland': onTheBottom,
  '18Mex': onTheBottom,
  '18MS': onTheBottom,
  '18Neb': onTheBottom,
  '18NL': onTheBottom,
  '18NW': onTheBottom,
  '18NY': onTheBottom,
  '18OE': onTheBottom,
  '18PA': onTheBottom,
  '18Rhl': onTheBottom,
  '18Ruhr': onTheBottom,
  '18Scan': onTheBottom,
  '18TN': onTheBottom,
  '18US': onTheBottom,
  '18USA': onTheBottom,
  '18VA': onTheBottom,
  '18West': onTheBottom,
  '2038': onTheBottom,
  'Poseidon': onTheBottom,
  '1800': unspecified,
  '1834': unspecified,
  '1835': unspecified,
  '1838 Rheinland': unspecified,
  '1846': unspecified,
  '1847': unspecified,
  '1848': unspecified,
  '1856': unspecified,
  '1857': unspecified,
  '1859': unspecified,
  '1862': unspecified,
  '1868': unspecified,
  '1870': unspecified,
  '1879': unspecified,
  '1880': unspecified,
  '1891': unspecified,
  '1895': unspecified,
  '18??': unspecified,
  '18C2C': unspecified,
  '18CLE': unspecified,
  '18Kaas': unspecified,
  '18MW': unspecified,
  '18NK': unspecified,
  '18SA': unspecified,
  '18SS': unspecified,
  '18SY': unspecified,
  '1825': notApplicable,
  '1829': notApplicable,
  '1829 Mainline': notApplicable,
  '1830BC': notApplicable,
  '1853': notApplicable,
  'Rolling Stock': notApplicable,
  '1830 Cardgame': 'Not applicable. Shares may not be sold at any time.',
  '1841': 'Unspecified in the original rules. A clarification means that the final order is the reverse of the original operating order.',
  '18EZ Level 1': 'Not Applicable (no share dealing).',
  'Railroad Barons': 'Unspecified, but irrelevant, as the tokens do not determine operating order.',
  'Steam Over Holland': 'Unspecified for stock sales; to the right of existing tokens for adjustments due to payment or otherwise of company dividends.',
  '1827Jr': 'Unknown', // TODO
  '1837': 'Unknown', // TODO
  '1842': 'Unknown', // TODO
  '1844': 'Unknown', // TODO
  '1849': 'Unknown', // TODO
  '1851': 'Unknown', // TODO
  '1854': 'Unknown', // TODO
  '1898': 'Unknown', // TODO
  '18EU': 'Unknown', // TODO
  'Crisis': 'Unknown', // TODO
};
