// 3.2 - How many shares must be sold for a company to float?

const twentyPercent = '20%.';
const thirtyPercent = '30%.';
const fiftyPercent = '50%.';
const sixtyPercent = '60%.';
const president = "The President's certificate.";
const styleMainline = "The Director's certificate, or three ordinary certificates.";
const style1841 = '20% (40% of a minor).';
const style1856 = 'Depends on the type of the train currently for sale.';
const style18fl = '60% for five-share companies, 50% for ten-share companies.';

export default {
  '1761': sixtyPercent,
  '1827Jr': sixtyPercent,
  '1829': sixtyPercent,
  '1830': sixtyPercent,
  '1832': sixtyPercent,
  '1834': sixtyPercent,
  '1837SX': sixtyPercent,
  '1848': sixtyPercent,
  '1850': sixtyPercent,
  '1859': sixtyPercent,
  '1862': sixtyPercent,
  '1865 Sardinia': sixtyPercent,
  '1868': sixtyPercent,
  '1869 The Golden Spike': sixtyPercent,
  '1869 USA West': sixtyPercent,
  '1873': sixtyPercent,
  '1879': sixtyPercent,
  '1895': sixtyPercent,
  '18C2C': sixtyPercent,
  '18EC': sixtyPercent,
  '18GA': sixtyPercent,
  '18GM': sixtyPercent,
  '18Kaas': sixtyPercent,
  '18MS': sixtyPercent,
  '18MW': sixtyPercent,
  '18NL': sixtyPercent,
  '18SS': sixtyPercent,
  '1800': fiftyPercent,
  '1826': fiftyPercent,
  '1835': fiftyPercent,
  '1837': fiftyPercent,
  '1838 Rheinland': fiftyPercent,
  '1842': fiftyPercent,
  '1844': fiftyPercent,
  '1847': fiftyPercent,
  '1847AE': fiftyPercent,
  '1851': fiftyPercent,
  '1854': fiftyPercent,
  '1857': fiftyPercent,
  '1860': fiftyPercent,
  '1862EA': fiftyPercent,
  '1889': fiftyPercent,
  '1893': fiftyPercent,
  '18BL': fiftyPercent,
  '18CZ': fiftyPercent,
  '18EU': fiftyPercent,
  '18EZ Level 2': fiftyPercent,
  '18EZ Level 3': fiftyPercent,
  '18GL': fiftyPercent,
  '18Mex': fiftyPercent,
  '18PA': fiftyPercent,
  '18Rhl': fiftyPercent,
  '18Ruhr': fiftyPercent,
  'Railroad Barons': fiftyPercent,
  'Rolling Stock': fiftyPercent,
  '1812': twentyPercent,
  '1846': twentyPercent,
  '1849': twentyPercent,
  '1861': twentyPercent,
  '1867': twentyPercent,
  '18SY': `G Rules: ${sixtyPercent}, O Rules: ${twentyPercent}`,
  '1817': president,
  '18USA': president,
  '1822': 'Initially 20% (10% for the LNWR) when converting a concession. From phase 5, 50%.',
  '1822CA': 'Initially 20% (10% for the CPR) when converting a concession. From phase 5, 50%.',
  '1824': '50% for regional railways and 20% for Staatsbahnen.',
  '1825': '60% for a major company, 40% for a minor company.',
  '1829 Mainline': styleMainline,
  '18Africa': styleMainline,
  '1830 Cardgame': 'One.',
  '1830BC': '6 (variable percentage).',
  '1831': '50% (all preferred stock).',
  '1841': style1841,
  '1898': style1841,
  '1853': 'v1: 3 or 4 players, 60%; 5 or 6 players, 50%. v2: 3 players, 60%; 4 or 5 players, 50%; 6 players, 40%.',
  '1856': style1856,
  '1891': style1856,
  '1858': '40% of a 5-share company, 20% of a 10-share company.',
  '1870': '60%; but 20% for the SLSF.',
  '1880': 'The qualifying number of shares depends on the phase. From Phase A1 (the start of the game) it is 20%, from B1 it is 30%, from B3 it is 40% and from C2 it is 60%.',
  '1881': 'Five certificates. This is 60% for tramway companies, 30% for the S-Bahn.',
  '18??': '60%; but 30% for any company started by the Grand Junction Investors private.',
  '18Ardennes': thirtyPercent,
  '18SA': thirtyPercent,
  '18CLE': "60%, except for the CSC, which floats at 20%. Rule 3.3.3 refers generally to a company as 'floated' when the 20% President's certificate has been bought - this should say 'started' or 'formed'.",
  '18Dixie': "50%, but 20% for the SAL and SOU if the President's certificates are obtained via the purchase of the GAR or SCCRRC private companies respectively.",
  '18EZ Level 1': 'Not Applicable (no share dealing).',
  '18FL': style18fl,
  '18NW': style18fl,
  '18GB': '40% in the yellow phase; 60% thereafter. No companies may be started in the grey phase.',
  '18Ireland': "40% for a 5-share company, 20% for a 10-share company, i.e. just the director's certificate in both cases.",
  '18Neb': '20% (40% of a Local Company).',
  '18NY': 'Dependent on the current game phase (see section 12).',
  '18OE': 'For minors, 100%. For regionals, 20%.',
  '18Scan': 'Depends on the current phase number.',
  '18TN': '60%, but only 20% for the L&N.',
  '18US': "For an Eastern (4-share) company, the President's certificate. For a Land Grant (5-share) company, the President's certificate and one other certificate.",
  '18VA': '20% for ten-share companies, 40% for five-share companies (one certificate in each case).',
  '18West': "The President's certificate. The v2.3 retuned rules clarify that after phase 6 begins, five shares must be bought to start a public company.",
  '2038': '50%; but 20% for growth companies.',
  'Crisis': '50% for type I companies, 60% for type II companies.',
  'Poseidon': 'At least 50% (rounded up) of the Ml Company).',
  '18NK': "60%; but 20% for the DRMerchants placed in the bank pool by the player who bought the nation's King card.",
  'Steam Over Holland': 'A number of shares equal to the current phase number, which have to be bought as one purchase.',
};
