// 5.4 - Do villages upgrade?

const betterDits = 'Yes, they stay as villages but acquire more connections.';
const notApplicable = 'Not applicable.';
const singleYesDoubleNo = 'Single villages upgrade, staying as villages but acquiring more connections. Double villages do not upgrade.';
const toCities = 'Yes, to cities.';
const no = 'No.';
const singleMoreConnectionsDoubleNo = 'Single villages do, acquiring more connections and eventually scoring more. Double villages do not.';
const ditsWithMoreConnections = 'Yes. They stay as villages, acquiring more connections, and eventually score more.';
const style1856 = "Yes. Once a 6-train is sold, all villages (except the 'bow-and-arrow' double) upgrade to cities, and single villages also downgrade to plain track.";
const moreConnectionsOrRevenue = 'Yes, they stay as villages but acquire more connections and/or higher revenue.';

export default {
  '1761': betterDits,
  '1800': betterDits,
  '1812': betterDits,
  '1822': betterDits,
  '1822CA': betterDits,
  '1826': betterDits,
  '1835': betterDits,
  '1838 Rheinland': betterDits,
  '1842': betterDits,
  '1844': betterDits,
  '1847': betterDits,
  '1847AE': betterDits,
  '1861': betterDits,
  '1865 Sardinia': betterDits,
  '1867': betterDits,
  '1869 USA West': betterDits,
  '1880': betterDits,
  '1881': betterDits,
  '18Ardennes': betterDits,
  '18BL': betterDits,
  '18CLE': betterDits,
  '18CZ': betterDits,
  '18Dixie': betterDits,
  '18FL': betterDits,
  '18GA': betterDits,
  '18GB': betterDits,
  '18Ireland': betterDits,
  '18Mex': betterDits,
  '18MS': betterDits,
  '18NK': betterDits,
  '18NL': betterDits,
  '18OE': betterDits,
  '18PA': betterDits,
  '18Ruhr': betterDits,
  '18West': betterDits,
  'Steam Over Holland': betterDits,
  '1817': notApplicable,
  '1830 Cardgame': notApplicable,
  '1830BC': notApplicable,
  '1831': notApplicable,
  '1837SX': notApplicable,
  '1846': notApplicable,
  '1851': notApplicable,
  '1868': notApplicable,
  '18C2C': notApplicable,
  '18SA': notApplicable,
  '18SS': notApplicable,
  '18USA': notApplicable,
  '2038': notApplicable,
  'Crisis': notApplicable,
  'Railroad Barons': notApplicable,
  '1824': singleYesDoubleNo,
  '1841': singleYesDoubleNo,
  '1858': singleYesDoubleNo,
  '18Africa': singleYesDoubleNo,
  '18NW': singleYesDoubleNo,
  '1825': toCities,
  '1829': toCities,
  '1869 The Golden Spike': toCities,
  '18Neb': toCities,
  '18NY': toCities,
  '1827Jr': no,
  '1830': no,
  '1834': no,
  '1848': no,
  '1857': no,
  '1859': no,
  '1879': no,
  '1889': no,
  '18EC': no,
  '18Kaas': no,
  '18SY': no,
  '1829 Mainline': 'Single villages do, either to villages with more connections or to cities. Double villages do not.',
  '1832': singleMoreConnectionsDoubleNo,
  '1850': singleMoreConnectionsDoubleNo,
  '1870': singleMoreConnectionsDoubleNo,
  '18??': singleMoreConnectionsDoubleNo,
  '18GL': singleMoreConnectionsDoubleNo,
  '1837': 'Yes, single villages acquire bypasses, double villages coalesce.',
  '1849': ditsWithMoreConnections,
  '1895': ditsWithMoreConnections,
  '18EU': ditsWithMoreConnections,
  '18EZ Level 1': ditsWithMoreConnections,
  '18EZ Level 2': ditsWithMoreConnections,
  '18EZ Level 3': ditsWithMoreConnections,
  '18Rhl': ditsWithMoreConnections,
  '18TN': ditsWithMoreConnections,
  '1853': "Single villages do, sometimes becoming cities; double villages don't.",
  '1854': "Double villages do. And from the brown phase, 'large villages' can be turned into cities by a yellow-to-yellow upgrade.",
  '1856': style1856,
  '1891': style1856,
  '1860': moreConnectionsOrRevenue,
  '18Scan': moreConnectionsOrRevenue,
  '1862': 'Yes, acquiring more connections and scoring more.',
  '1862EA': 'Yes, to track tiles, upon which a small station marker is placed to indicate which track the small station is on.',
  '1873': 'What the 1873 rules call villages are what other 18xx games call towns or cities. There are no classic villages in 1873.',
  '1893': 'Single villages upgrade to villages with more connections, and for brown tiles, increased value. Double villages upgrade to cities.',
  '1898': 'Villages may be upgraded to cities (green, brown, grey); single villages may be downgraded (green-brown, grey).',
  '18GM': 'Yes. Once a 6-train is sold, all villages upgrade to cities, and single villages also downgrade to plain track.',
  '18MW': 'Yes. Once an 8 train is sold, all villages upgrade to yellow cities, and downgrade to yellow plain track.',
  '18US': 'Villages arrive due to upgrades to plain yellow track tiles. They then stay as villages, acquiring more connections and scoring more.',
  '18VA': 'Coal mines upgrade, acquiring more track, but do not increase in value.',
  'Poseidon': notApplicable,
  'Rolling Stock': notApplicable,
};
