// 3.1 - Do you lay the base station token immediately upon floating?

const no = 'No.';
const yes = 'Yes.';
const style1817 = "A company's home station is placed when the President's certificate is put up for auction.";
const style1825 = 'The token is placed on the home base at the start of the operating round in which it will first run.';
const notApplicable = 'Not applicable.';
const startOfGame = 'All base station tokens start the game on the map.';

export default {
  '1761': no,
  '1800': no,
  '1822': no,
  '1822CA': no,
  '1824': no,
  '1827Jr': no,
  '1829': no,
  '1830': no,
  '1831': no,
  '1832': no,
  '1834': no,
  '1837SX': no,
  '1844': no,
  '1848': no,
  '1850': no,
  '1854': no,
  '1856': no,
  '1862': no,
  '1862EA': no,
  '1869 USA West': no,
  '1870': no,
  '1889': no,
  '1893': no,
  '1895': no,
  '18??': no,
  '18BL': no,
  '18C2C': no,
  '18CZ': no,
  '18Dixie': no,
  '18EC': no,
  '18EZ Level 1': no,
  '18EZ Level 2': no,
  '18EZ Level 3': no,
  '18GA': no,
  '18Kaas': no,
  '18Mex': no,
  '18MS': no,
  '18NK': no,
  '18NL': no,
  '18NY': no,
  '18Rhl': no,
  '18Ruhr': no,
  '18SA': no,
  '18SS': no,
  '18SY': no,
  '18TN': no,
  'Crisis': no,
  'Steam Over Holland': no,
  '1812': yes,
  '1826': yes,
  '1829 Mainline': yes,
  '1835': yes,
  '1837': yes,
  '1838 Rheinland': yes,
  '1841': yes,
  '1842': yes,
  '1846': yes,
  '1849': yes,
  '1851': yes,
  '1853': yes,
  '1858': yes,
  '1860': yes,
  '1861': yes,
  '1868': yes,
  '1873': yes,
  '1898': yes,
  '18Africa': yes,
  '18Ardennes': yes,
  '18EU': yes,
  '18GB': yes,
  '18GL': yes,
  '18Ireland': yes,
  '18MW': yes,
  '18Neb': yes,
  '18NW': yes,
  '18Scan': yes,
  '18VA': yes,
  '1817': style1817,
  '18USA': style1817,
  '1825': style1825,
  '1847': style1825,
  '1847AE': style1825,
  '1830 Cardgame': notApplicable,
  '1830BC': notApplicable,
  'Railroad Barons': notApplicable,
  'Rolling Stock': notApplicable,
  '1859': startOfGame,
  '1879': startOfGame,
  '18FL': startOfGame,
  '18PA': startOfGame,
  '18US': startOfGame,
  '18West': startOfGame,
  '1865 Sardinia': "All base station tokens start the game on the map. For absorbed companies re-entering the game the home base is placed when the President's certificate is purchased.",
  '1867': 'Yes, for public companies. For minor companies, the token is placed on a valid empty city circle on the map when the minor is put up for auction.',
  '1869 The Golden Spike': "Contradictory. The sections on home bases and floating the company state that the token is placed at the start of the company's first operating turn, while the section of placing station markers says that the home bases were placed when the company was started.",
  '1880': 'The token is placed on the home base at the end of the stock round in which the Director owns the qualifying number of shares. The qualifying number of shares depends on the phase. From Phase A1 (the start of the game) it is 20%, from B1 it is 30%, from B3 it is 40% and from C2 it is 60%.',
  '1881': 'It is recommended that base tokens for the tramway companies are placed upside down on their starting hexes at the beginning of the game. The rules do not say when these are flipped over, but it is assumed this happens when the tramway companies float, because the rules do state that the base tokens for the S-Bahn main company and its three subnets are placed when the S-Bahn floats.',
  '1891': 'Contradictory. As per the 1856 rules, which 1891 is based on, no, and the translated rules state that the token is placed when it first operates. However, the rules on starting a company have an italicised section that states that the token is placed in the starting city when the presidency is purchased.',
  '18CLE': "No. It is placed face down when the President's certificate is bought and turned face up when it first operates.",
  '18GM': "A company's home station marker is placed when the president's certificate is purchased, but imposes no restrictions (other than reserving the space) until the company operates for the first time.",
  '18OE': 'For minors, yes. Tokens for regionals start on the map.',
  '2038': 'Yes (relevant only for the Asteroid League).',
  'Poseidon': 'No (it is pre-printed on the map).',
  '1857': 'Unknown', // TODO
  '18Africa': 'Unknown', // TODO
};
