// 2.7 - Does the stock price drop when stock is sold?

const oneRowPerBlockByPresident = 'Yes, 1 row per block of shares sold, but only if they are sold by the company Director/President.';
const oneRowPerBlock = 'Yes, 1 row per block of shares sold.';
const no = 'No.';
const oneRowPerShare = 'Yes, 1 row per share.';
const ledge = "Yes, 1 row per share, but if this means it would end up one row below the ledge, then it stops above the ledge. Share prices do not change until after a player's stock turn and any ensuing 'price protection'.";
const oneColumnPerBlockByPresident = 'Yes, 1 column per block of shares sold, but only when sold by the company President.';

export default {
  '1761': oneRowPerBlockByPresident,
  '1812': oneRowPerBlockByPresident,
  '1858': oneRowPerBlockByPresident,
  '1861': oneRowPerBlockByPresident,
  '1867': oneRowPerBlockByPresident,
  '18Ruhr': oneRowPerBlockByPresident,
  'Poseidon': oneRowPerBlockByPresident,
  'Railroad Barons': oneRowPerBlockByPresident,
  '1800': oneRowPerBlock,
  '1824': oneRowPerBlock,
  '1835': oneRowPerBlock,
  '1838 Rheinland': oneRowPerBlock,
  '1844': oneRowPerBlock,
  '1847': oneRowPerBlock,
  '1847AE': oneRowPerBlock,
  '1848': oneRowPerBlock,
  '1862': oneRowPerBlock,
  '1881': oneRowPerBlock,
  '1893': oneRowPerBlock,
  '1895': oneRowPerBlock,
  '18Rhl': oneRowPerBlock,
  '2038': oneRowPerBlock,
  '1817': no,
  '1825': no,
  '1829': no,
  '1829 Mainline': no,
  '1853': no,
  '18Africa': no,
  '18SS': no,
  '18USA': no,
  '1822': oneRowPerShare,
  '1826': oneRowPerShare,
  '1830': oneRowPerShare,
  '1834': oneRowPerShare,
  '1837SX': oneRowPerShare,
  '1841': oneRowPerShare,
  '1849': oneRowPerShare,
  '1851': oneRowPerShare,
  '1857': oneRowPerShare,
  '1859': oneRowPerShare,
  '1868': oneRowPerShare,
  '1869 USA West': oneRowPerShare,
  '1879': oneRowPerShare,
  '1880': oneRowPerShare,
  '1889': oneRowPerShare,
  '1898': oneRowPerShare,
  '18BL': oneRowPerShare,
  '18Dixie': oneRowPerShare,
  '18EC': oneRowPerShare,
  '18EU': oneRowPerShare,
  '18EZ Level 2': oneRowPerShare,
  '18EZ Level 3': oneRowPerShare,
  '18GA': oneRowPerShare,
  '18GL': oneRowPerShare,
  '18GM': oneRowPerShare,
  '18Ireland': oneRowPerShare,
  '18Kaas': oneRowPerShare,
  '18Mex': oneRowPerShare,
  '18MS': oneRowPerShare,
  '18MW': oneRowPerShare,
  '18Neb': oneRowPerShare,
  '18NL': oneRowPerShare,
  '18NW': oneRowPerShare,
  '18NY': oneRowPerShare,
  '18OE': oneRowPerShare,
  '18PA': oneRowPerShare,
  '18Scan': oneRowPerShare,
  '18SY': oneRowPerShare,
  '18TN': oneRowPerShare,
  '18VA': oneRowPerShare,
  'Crisis': oneRowPerShare,
  '1822CA': 'Yes, 1 row per share if sold by the Director, or 1 row per block if sold by any other player.',
  '1827Jr': 'Complex. See table in rule 3.3.2 or http://www.fwtwr.com/18xx/rules_difference_list/1827_junior.htm.',
  '1830 Cardgame': 'Not applicable. Shares may not be sold at any time.',
  '1830BC': 'Yes, 1 place per share, maximum 3 per block (1 in red zone).',
  '1831': 'No for preferred stock, complex for common stock.',
  '1832': ledge,
  '1850': ledge,
  '1870': ledge,
  '18??': ledge,
  '1837': 'Yes, 1 row (down and to the left) per block.',
  '1842': 'Yes, 1 row for a sale of 10% or 20%; 2 rows for a sale of 30% or more.',
  '1846': oneColumnPerBlockByPresident,
  '18US': oneColumnPerBlockByPresident,
  '18West': oneColumnPerBlockByPresident,
  '1854': 'Yes, 1 row (down and to the left) per certificate.',
  '1856': "Yes, 1 row per complete 10% sold; e.g. selling 25% drops the price two rows. The CGR's price cannot change for any reason until it owns a permanent train.",
  '1860': 'Yes, if the company has operated.The price moves down once for each share sold, zig-zagging between the top and bottom levels. However, when shares are worth less than 40 or more than 150, the first share sold has no effect on the share price, i.e. the price moves down one less space than normal. Once the 8+4 train is bought, sales do not reduce share prices.',
  '1862EA': 'Yes, 1 space per share sold. However, if the share price is above 200 or below 40, and the seller is not the company Director, ignore the first certificate sold. If the price is above 400, ignore the first 2 shares sold. The share price does not fall if the company has not floated, or after the sale of the first H train.',
  '1865 Sardinia': 'Yes, 1 row per share sold, but only if they are sold by the company President or a Dragon (foreign investor).',
  '1869 The Golden Spike': "Yes, 1 row per share from the player's hand, but 1 row per block of grworth shares.",
  '1873': 'Yes, 1 row per share,m but only if it has already operated.',
  '1891': "Yes, 1 row per complete 10% sold; e.g. selling 25% drops the price two rows. The JNR's price cannot change for any reason until it owns a permanent train.",
  '18Ardennes': 'Yes, 1 row per share sold, but only if they are sold by the company President.',
  '18C2C': 'Yes, 1 row per share; but if this would take it to just below ledge, then 1 less.',
  '18CLE': 'Yes, 1 row per share, but if the token is immediately above the ledge, the number of spaces dropped is reduced by 1.',
  '18CZ': 'Yes, the price moves down once for each share sold, zig-zagging between the top and bottom levels.',
  '18EZ Level 1': 'Not Applicable (no share dealing).',
  '18FL': 'Yes, 1 column to the left per block.',
  '18GB': 'Yes, one space per share sold, except that in the grey phase sales by non-directors do not affect the price.',
  '18NK': 'Yes, one row per complete 20% sold.',
  '18SA': 'Yes. In the yellow zone, 1 row per 5% sold, in other areas of the stock market, 1 row per 10% sold.',
  'Rolling Stock': 'Yes, at least 1 place per share, possibly more by leapfrogging. You may only sell one share at a time, and you get paid the lowered share price.',
  'Steam Over Holland': 'Yes, 1 row per share, but if sold by someone other than the president, can not drop below a ledge. If sold by a company during an OR, it drops 1 row less than the number of shares sold.',
};
