// 1.4 - Can you make advance bids?

const no = 'No.';
const yesStandard = 'Yes, at 5 or more over par and over any other bid.';
const yes1822 = 'Yes, at face value of the item or a multiple of 5 over any other bid.';
const yesMultipleFive = 'Yes, at a multiple of 5 over par and over any other bid.';
const notApplicable = 'Not applicable.';
const saleByTender = 'Initial sale is by tender.';
const yesFiveOverParOrCurrentBid = 'Yes, at 5 over par or the current highest bid.';
const yesFirstAtPar = 'Yes, the first on a private must be at par, others must be at least 5 over any other bid.';
const yesFaceOrFiveOver = 'Yes. The bid must be at face value or a multiple of 5 over it or any previous bid.';

export default {
  '1761': no,
  '1800': yesStandard,
  '1812': no,
  '1817': 'Yes. The bid plus the available seed money from the bank must be at face value or a multiple of 5 over it or any previous bid.',
  '1822': yes1822,
  '1822CA': yes1822,
  '1824': no,
  '1825': no,
  '1826': yesMultipleFive,
  '1827Jr': yesStandard,
  '1829 Mainline': notApplicable,
  '1829': no,
  '1830 Cardgame': notApplicable,
  '1830': yesStandard,
  '1830BC': yesStandard,
  '1831': notApplicable,
  '1832': yesStandard,
  '1834': yesStandard,
  '1835': no,
  '1837': no,
  '1837SX': no,
  '1838 Rheinland': no,
  '1841': saleByTender,
  '1842': no,
  '1844': no,
  '1846': notApplicable,
  '1847': no,
  '1847AE': no,
  '1848': no,
  '1849': `Yes, at 5 over any other bid, for the initial concessions. v4: ${yesStandard}`,
  '1850': yesStandard,
  '1851': no,
  '1853': notApplicable,
  '1854': yesStandard,
  '1856': yesStandard,
  '1857': no,
  '1858': no,
  '1859': yesStandard,
  '1860': no,
  '1861': no,
  '1862': yesStandard,
  '1862EA': notApplicable,
  '1865 Sardinia': notApplicable,
  '1867': no,
  '1868': yesStandard,
  '1869 The Golden Spike': yesFiveOverParOrCurrentBid,
  '1869 USA West': yesMultipleFive,
  '1870': yesStandard,
  '1873': no,
  '1879': notApplicable,
  '1880': yesMultipleFive,
  '1881': notApplicable,
  '1889': yesStandard,
  '1891': yesStandard,
  '1893': notApplicable,
  '1895': no,
  '1898': saleByTender,
  '18??': yesFaceOrFiveOver,
  '18Africa': no,
  '18Ardennes': no,
  '18BL': yesMultipleFive,
  '18C2C': yesStandard,
  '18CLE': yesStandard,
  '18CZ': `Standard game and Bohemia Variant: ${notApplicable}, Moravia-Silesia Variant: ${yesFirstAtPar}`,
  '18Dixie': no,
  '18EC': yesStandard,
  '18EU': no,
  '18EZ Level 1': notApplicable,
  '18EZ Level 2': notApplicable,
  '18EZ Level 3': yesStandard,
  '18FL': 'No. Privates are bought at face value, following a bidding process to determine the order in which players make their purchases.',
  '18GA': yesStandard,
  '18GB': "Yes, at a multiple of 5 over par and over any other bid. These are not strictly 'advance' bids as all privates are auctioned simultaneously.",
  '18GL': yesMultipleFive,
  '18GM': yesFiveOverParOrCurrentBid,
  '18Ireland': yesMultipleFive,
  '18Kaas': yesStandard,
  '18MS': no,
  '18MW': yesFirstAtPar,
  '18Mex': yesStandard,
  '18NK': yesStandard,
  '18NL': yesStandard,
  '18NW': yesMultipleFive,
  '18NY': yesMultipleFive,
  '18Neb': 'Yes, the first may be at par, later bids must be at a multiple of 5 over the last bid.',
  '18OE': 'Yes, at face value of the item or at least 5 over any other bid.',
  '18PA': yesMultipleFive,
  '18Rhl': yesStandard,
  '18Ruhr': no,
  '18SA': yesFiveOverParOrCurrentBid,
  '18SS': yesStandard,
  '18SY': yesStandard,
  '18Scan': 'No, but bids are made in multiples of 5 for the right to make the next purchase.',
  '18TN': yesStandard,
  '18US': notApplicable,
  '18USA': yesFaceOrFiveOver,
  '18VA': yesMultipleFive,
  '18West': `v1.0: ${notApplicable}, v2.3 retuned: ${no}`,
  '2038': 'Yes, at or over par and 5 or more over any other bid.',
  'Crisis': notApplicable,
  'Poseidon': no,
  'Railroad Barons': no,
  'Rolling Stock': no,
  'Steam Over Holland': no,
};
