// 5.3 - Must a tile replacement extend existing track?

const permissive = "Permissive: Some of the track on the newly-laid tile must be reachable from one of the laying company's station markers by an arbitrarily large train.";
const restrictive = "Restrictive: Some of the newly-created track must be reachable from one of the laying company's station markers by an arbitrarily large train.";
const semiRestrictive = "Semi-restrictive: Some of the newly-created track must be reachable from one of the laying company's station markers by an arbitrarily large train or the value of a city which can be reached by that train changes.";
const notApplicable = 'Not applicable.';

const style1861 = 'Restrictive for track tiles, for city upgrades, some track (old or new) must be part of a route for the company.';

export default {
  '1761': permissive,
  '1800': semiRestrictive,
  '1812': style1861,
  '1817': permissive,
  '1822': permissive,
  '1822CA': permissive,
  '1824': permissive,
  '1825': `${restrictive} In addition, a city may only be upgraded if reachable from one of the laying company's station-markers by 'one of the Company's existing Trains' (rule 4.3.2). Two '2' trains can be double-headed to act as a single '3' train for this purpose. (rule 4.5.5). {Following this to the letter raises issues when upgrading some station tiles. For example, London has no new track, while the Birmingham/Glasgow/Manchester tiles have new track for only one station, so a company could only upgrade it if it was using this track. Having talked with Francis Tresham it was clearly not the intention to create such a restriction, so you can consider that his intention was for semi-restrictive upgrades. However, the requirement to be able to reach a station with one of the company's trains still exists.}; With survey parties As for 1825 without them (rule 6.6).`,
  '1826': semiRestrictive,
  '1827Jr': `${permissive} (personal communication to Nick Wedd from Vellani).`,
  '1829': 'The upgrading company must have moved a Survey Party, and the upgraded hex must be free of Survey Parties (rule 43).',
  '1829 Mainline': `${restrictive} In addition, a city may only be upgraded if reachable from one of the laying company's station-markers by one of the company's existing trains.`,
  '1830': `v1: Rule 18.1 says permissive. However it is possible to read the restrictions of rule 18.0 as applying to rule 18.1, making the result restrictive. A clarification from Avalon Hill says that the 1830 rule is semi-restrictive. Their own computer version is permissive. v2 & v3: ${permissive}`,
  '1830 Cardgame': notApplicable,
  'Railroad Barons': notApplicable,
  '1830BC': notApplicable,
  '2038': notApplicable,
  '1831': `${permissive} (rule 5.2.6.5).`,
  '1832': semiRestrictive,
  '1834': 'As for 1830, except that in the Green phase, a company may pay 50 to place a green tile directly on the map, skipping the normal yellow tile placement.',
  '1835': `${restrictive} (German rule VII.1). But the author's intention was permissive, and another German ruleset exists. An English translation says permissive (rules 3.1.12-3.1.20).`,
  '1837': 'According to the printed rules, restrictive (rule VI.1). This means that certain tiles can never be laid, and is a mistake. The designer Leonhard Orgler has stated (personal communication to Steve Thomas) that it should be semi-restrictive.',
  '1837SX': `${semiRestrictive} However, there is no requirement for a city value to change.`,
  '1838 Rheinland': semiRestrictive,
  '1841': 'The original rules were restrictive (rules 4.1.1, 4.1.2). As for 1837, a subsequent clarification from the author states that it should be semi-restrictive.',
  '1842': `${restrictive} (rule 6.2.3). (Note also rule 6.2.2 restricting upgrades to both coastal and inland cities.)`,
  '1844': `${permissive} (rule XV, bullet-point 7).`,
  '1846': semiRestrictive,
  '1847': `As for 1835 - presumably restrictive. ${restrictive}`,
  '1847AE': semiRestrictive,
  '1848': permissive,
  '1849': `v1&3: ${restrictive}. v4: ${semiRestrictive}`,
  '1850': 'Semi-restrictive, except that the value of a town or city need not change.',
  '1851': semiRestrictive,
  '1853': "Permissive; but upgrades only allowed on the company's 'patch'. A brown tile next to a grey tile may not be upgraded (i.e. there can never be two grey tiles adjacent to each other).",
  '1854': `${semiRestrictive} (rule 5.4).`,
  '1856': semiRestrictive,
  '1857': permissive,
  '1858': `${semiRestrictive} (rule 9.3).`,
  '1859': permissive,
  '1860': `${semiRestrictive} Furthermore, the tile being upgraded must be reachable from one of the laying company's station-markers by one the company's existing trains. Unlike 1825, this additional restriction is not limited to station tiles.`,
  '1861': style1861,
  '1862': permissive,
  '1862EA': `${permissive} (rule.7.6.1).`,
  '1865 Sardinia': `${restrictive} (page 22).`,
  '1867': style1861,
  '1868': permissive,
  '1869 The Golden Spike': semiRestrictive,
  '1869 USA West': "Some of the track on the original tile must be reachable from one of the laying company's station markers by an arbitrarily large train.",
  '1870': `${semiRestrictive} (page 20).`,
  '1873': "Super-restrictive. After being laid, all new track on the tile must be reachable from any of the laying company's station markers by an arbitrarily large train.",
  '1876v2': `${permissive} ('.. use the 1830 rulebook').`,
  '1879': permissive,
  '1880': permissive,
  '1881': `${restrictive} (rule 7.2.1.2).`,
  '1889': semiRestrictive,
  '1891': semiRestrictive,
  '1893': semiRestrictive,
  '1895': permissive,
  '1898': `${permissive} (final sentence of section 'Lay or Upgrade Track').`,
  '18??': `${semiRestrictive} (page 20 of the 1870 rules).`,
  '18Africa': restrictive,
  '18Ardennes': semiRestrictive,
  '18BL': restrictive,
  '18C2C': `${semiRestrictive} (last but one paragraph of section 4.7.1).`,
  '18CLE': `${semiRestrictive} (rule 4.1). In addition, a company may only upgrade a station tile from green to brown if it has a token on that tile.`,
  '18CZ': `${permissive} (bullet point 8 of section VIII.5).`,
  '18Dixie': semiRestrictive,
  '18EC': permissive,
  '18EU': semiRestrictive,
  '18EZ Level 1': permissive,
  '18EZ Level 2': permissive,
  '18EZ Level 3': permissive,
  '18FL': semiRestrictive,
  '18GA': semiRestrictive,
  '18GB': restrictive,
  '18GL': semiRestrictive,
  '18GM': semiRestrictive,
  '18Ireland': semiRestrictive,
  '18Kaas': permissive,
  '18Mex': `${semiRestrictive} But there is no requirement for a city value to change.`,
  '18MS': semiRestrictive,
  '18MW': permissive,
  '18Neb': semiRestrictive,
  '18NK': semiRestrictive,
  '18NL': permissive,
  '18NW': restrictive,
  '18NY': permissive,
  '18OE': semiRestrictive,
  '18PA': semiRestrictive,
  '18Rhl': semiRestrictive,
  '18Ruhr': permissive,
  '18SA': permissive,
  '18Scan': semiRestrictive,
  '18SS': semiRestrictive,
  '18SY': permissive,
  '18TN': semiRestrictive,
  '18US': semiRestrictive,
  '18USA': permissive,
  '18VA': semiRestrictive,
  '18West': semiRestrictive,
  'Crisis': permissive,
  'Poseidon': notApplicable,
  'Rolling Stock': notApplicable,
  'Steam Over Holland': permissive,
};
