// 5.2 - Can you lay two tiles in a turn?

const no = 'No.';
const style1861 = 'Yes, on payment of a fee a second tile operation may be performed, but only one of the two tile operations may be an upgrade. You may not lay a tile and upgrade it in the same turn.';
const style1822 = 'From phase 3 onwards, a major company may lay two yellow tiles or upgrade one tile.';
const onlyWithPrivate = 'Only by using the special property of a private.';
const notApplicable = 'Not applicable.';
const style1835 = 'Only by major companies before first 3 train sold.';
const style1846 = 'Yes, each round a company may lay two yellow tiles or lay one yellow tile and upgrade one tile.';
const style1848 = 'Yes, once a 3 train has been sold. Two yellow tiles only.';
const style1850 = "Yes, if both are yellow and it is the company's first turn.";
const ifBothYellow = 'Yes, if both are yellow.';
const secondYellowInFirstOR = 'Yes, a second yellow tile in its first OR.';

export default {
  '1761': 'A second tile may be laid on payment of a fee of 10. Once the first 4 train has been purchased, a third tile may be laid for a further payment of 10.',
  '1800': no,
  '1824': no,
  '1829': no,
  '1837': no,
  '1844': no,
  '1849': no,
  '1854': no,
  '1879': no,
  '1893': no,
  '18EZ Level 1': no,
  '18EZ Level 2': no,
  '18EZ Level 3': no,
  '18NL': no,
  '18Scan': no,
  '18SY': `G version: ${no}, O version: You may lay or upgrade one tile from each token a company has on the map. The same hex may be upgraded multiple times if the company has multiple tokens connected to that hex.`,
  '18VA': no,
  '1812': style1861,
  '1817': style1861,
  '1861': style1861,
  '1867': style1861,
  '18USA': style1861,
  '1822': style1822,
  '1822CA': style1822,
  '1825': 'Yes, if neither is an upgrade and they are not adjacent.',
  '1826': "Yes, if neither is a upgrade and it is the company's first turn.",
  '1827Jr': 'For mid-west companies if both tiles are west of starting hex.',
  '1829 Mainline': 'You may lay any number of yellow tiles as long as the track laid is continuous. This continuous route can be traced through pre-printed track in a brown board hex. Track laying must finish if a connection is made to an existing city. It must also finish if a tile of types 3, 6, 7 or 115 is laid. If the Midland, NER or NBR need to lay a tile on their home hex when they frst operate, this lay is in addition to any other tile laying activities for that round.',
  '1830': onlyWithPrivate,
  '1856': onlyWithPrivate,
  '1857': onlyWithPrivate,
  '1859': onlyWithPrivate,
  '1869 USA West': onlyWithPrivate,
  '1889': onlyWithPrivate,
  '1891': onlyWithPrivate,
  '18EC': onlyWithPrivate,
  '18GA': onlyWithPrivate,
  '18Kaas': onlyWithPrivate,
  '18Rhl': onlyWithPrivate,
  '1830 Cardgame': notApplicable,
  'Railroad Barons': notApplicable,
  '1830BC': 'Yes, and more, depending on quality of digging team.',
  '1831': 'Yes. Four-fold by a company, seven-fold by a system.',
  '1832': 'Yes, if both are yellow. Systems may lay three yellow tiles or lay one yellow tile and upgrade another.',
  '1834': 'No, but using the special property of the Burbach Foundry private, an additional upgrade to a Luxembourg city may be carried out.',
  '1835': style1835,
  '1838 Rheinland': style1835,
  '1837SX': 'Yes, if there are sufficient building points and the build does not include the initial lay of a viaduct tile.',
  '1841': 'Majors may do one tile lay or upgrade from each station-marker until a 3 train, then one from each up to a limit of 2 until a 5 train. But never more than one tile change on same hex.',
  '1842': "Yes, but only on a share company's first OR, and not both on the same hex.",
  '1846': style1846,
  '18Neb': style1846,
  '1847': 'Yes, during the Yellow phase only.',
  '1847AE': "Yes, throughout the Yellow phase, or if it is the company's first operating round.",
  '1848': style1848,
  '1851': style1848,
  '1862': style1848,
  '1850': style1850,
  '18BL': style1850,
  '18CZ': style1850,
  '1858': 'Yes, for a fee of 20 (only 10 if all new track on one tile is narrow gauge). Both can be upgrades, but they must be in different hexes.',
  '1860': 'Yes if both are yellow and neither contains a large station.',
  '1862EA': 'Yes, if both are yellow and neither are N tiles.',
  '1865 Sardinia': 'Yes, on payment of a fee a second tile operation may be performed.',
  '1868': 'Yes, a company may place or upgrade two track tiles at a cost of 10.',
  '1869 The Golden Spike': 'Yes. Companies may lay a number of tiles based on tile points. Each company has 3 tile points available. Most tile actions cost 1 point, but laying a yellow tile in a mountain hex or upgrading a city to russet or grey costs 2 points.',
  '1870': 'Yes, if both are yellow. Purchase of the MRBC by the MP or SSW can allow a third tile to be laid.',
  '1873': 'Concession routes are always built in one step, which can involve up to 5 tiles. For normal track lays and upgrades, two tiles can be placed if each tile is either yellow or a green tile with two completely separate sections of track.',
  '1880': 'Yes, once a 3 train has been sold, if both are yellow. The BCR may lay two yellow tiles from the start of the game. However, Foreign Investors only ever lay one tile in a turn.',
  '1881': 'Yes, tramway companies can place two yellow tiles in the Yellow phase.',
  '1895': 'Yes, once an 8H train has been sold. Two yellow tiles only.',
  '1898': 'Majors may do one tile lay or upgrade from each station marker until a 3 train, then one from each up to a limit of 2 until end of turn. But never more than one tile change on same hex. Minors may do one tile lay or upgrade until a 4 train, then one from each station marker until end of game.',
  '1853': 'v1: First four companies only. Each lay must be connected to a different station marker and the connecting routes must not use the same piece of track at any point. v2: First four companies only, and possible company 5 if it forms as a major company during the contract bidding stage. Each lay must be connected to a different station marker and the connecting routes must not use the same piece of track at any point. When they first operate, each of these companies must choose to either delay the ability to lay two tiles until Phase 3, or to gain the ability immediately. If the ability is gained immediately, the company must pay the bank every time that two tiles are laid. Company 1 must pay £50 to lay two tiles, companies 2 to 5 must pay £20 to lay two tiles.',
  '18??': ifBothYellow,
  '18FL': ifBothYellow,
  '18MW': ifBothYellow,
  '18NK': ifBothYellow,
  '18PA': ifBothYellow,
  '18Africa': 'Up to four yellow track tiles as long as the track is continuous, or for the first turn of companies starting on double-city hexes, one green then three yellows. This continuous route can be traced through pre-printed track in a brown board hex. Track laying must finish if a connection is made to an existing city. It must also finish if a tile of types 3, 6, 7 or 115 is laid.',
  '18Ardennes': 'Yes, for public companies only. They may lay two yellow tiles or upgrade one tile.',
  '18C2C': 'Yes. Tiles are laid on a points basis. It is possible to lay up to four yellow tiles in one turn.',
  '18CLE': 'Yes. Companies may lay two yellow tiles during phase 2.',
  '18Dixie': 'Major companies normally lay up to two tiles each operating turn. All companies may lay one extra yellow tile on their first operating turn.',
  '18EU': 'Yes, for a minor company in its first OR.',
  '18GB': 'Yes, but at most one may be in a city. Both may be upgrades.',
  '18GL': 'Yes, for any company other than CONRAIL in its first OR.',
  '18GM': 'Yes. Two yellow tiles may be laid in clear terrain, two non-city track tiles may be upgraded to green or russet, or one each of these actions.',
  '18Ireland': 'Yes, on payment of a fee a second tile may be laid.',
  '18Mex': 'Yes, for major companies only.',
  '18MS': secondYellowInFirstOR,
  '18NW': secondYellowInFirstOR,
  '18NY': 'Yes, either two tile lays or one tile lay and one upgrade, subject to sufficient funds being available.',
  '18OE': 'Yes. Companies may lay a number of tiles based on available tile points. Different company types have different tile points available, and different tile types/actions cost different numbers of points.',
  '18Ruhr': 'Yes, either two yellow tiles or one yellow tile and one upgrade. You may not lay a tile and upgrade it in the same turn.',
  '18SA': 'No, except for companies that start operating in the Brown phase. These companies may lay/upgrade two tiles in their first operating turn.',
  '18SS': 'Yes, you may lay two tiles, lay one tile and upgrade another, or upgrade two tiles. You may not upgrade the tile just laid or upgraded with your second tile action.',
  '18TN': 'Yes, if both are yellow. Ownership of private companies can allow additional tiles to be laid.',
  '18US': 'Yes, for Systems. Land Grant companies can lay up to three yellow tiles or lay two yellow tiles and upgrade one yellow tile to green if it can pay any required costs from its treasury.',
  '18West': 'Yes, for public companies. Land Grant companies can lay or upgrade up to three tiles (four tiles, up to two from each of its railheads, under the v2.3 retuned rules).',
  '2038': 'Yes, multiple exploration allowed.',
  'Crisis': 'No, except that a green tile must be laid alongside a yellow one if available.',
  'Poseidon': notApplicable,
  'Rolling Stock': notApplicable,
  'Steam Over Holland': 'Yes, each round a company may lay two yellow tiles or lay one yellow tile and upgrade one tile, which can be the tile just laid.',
};

/*
*/
