// 2.1 - Is there a specific order to buying and selling on your turn?

const sellThenBuy = 'Sell, then Buy';
const sellBuySell = 'No (i.e. sell-buy-sell).';
const sellBuyOrBuySell = 'Sell then buy, or buy then sell.';

export default {
  '1761': sellThenBuy,
  '1812': sellThenBuy,
  '1817': sellThenBuy,
  '1822': sellThenBuy,
  '1822CA': sellThenBuy,
  '1824': sellThenBuy,
  '1826': sellThenBuy,
  '1827Jr': sellThenBuy,
  '1831': sellThenBuy,
  '1841': sellThenBuy,
  '1842': sellThenBuy,
  '1844': sellThenBuy,
  '1846': sellThenBuy,
  '1847': sellThenBuy,
  '1847AE': sellThenBuy,
  '1848': sellThenBuy,
  '1849': sellThenBuy,
  '1851': sellThenBuy,
  '1854': sellThenBuy,
  '1858': sellThenBuy,
  '1860': sellThenBuy,
  '1861': sellThenBuy,
  '1862': sellThenBuy,
  '1862EA': sellThenBuy,
  '1865 Sardinia': sellThenBuy,
  '1867': sellThenBuy,
  '1869 USA West': sellThenBuy,
  '1873': sellThenBuy,
  '1880': sellThenBuy,
  '1893': sellThenBuy,
  '1895': sellThenBuy,
  '1898': sellThenBuy,
  '18Ardennes': sellThenBuy,
  '18BL': sellThenBuy,
  '18CZ': sellThenBuy,
  '18EU': sellThenBuy,
  '18FL': sellThenBuy,
  '18GB': sellThenBuy,
  '18GL': sellThenBuy,
  '18Ireland': sellThenBuy,
  '18Neb': sellThenBuy,
  '18NW': sellThenBuy,
  '18OE': sellThenBuy,
  '18PA': sellThenBuy,
  '18Rhl': sellThenBuy,
  '18Ruhr': sellThenBuy,
  '18SA': sellThenBuy,
  '18Scan': sellThenBuy,
  '18SS': sellThenBuy,
  '18US': sellThenBuy,
  '18USA': sellThenBuy,
  '18VA': sellThenBuy,
  '18West': sellThenBuy,
  '2038': sellThenBuy,
  'Railroad Barons': sellThenBuy,
  'Steam Over Holland': sellThenBuy,
  '1800': 'No.',
  '1825': sellBuySell,
  '1829': sellBuySell,
  '1830': `${sellBuySell} (Note: v1 Sell then buy, or buy then sell. But the author's intention was to allow sell-buy-sell, and many people, also the computer version, allow this.`,
  '1830BC': sellBuySell,
  '1835': sellBuySell,
  '1838 Rheinland': sellBuySell,
  '1853': sellBuySell,
  '1881': sellBuySell,
  '18MW': sellBuySell,
  'Poseidon': sellBuySell,
  '1829 Mainline': 'Shares can be sold at the beginning of a stock ROUND (not each turn). Shares may then be purchased from a number of sources.',
  '1830 Cardgame': 'Not applicable. Shares may not be sold at any time.',
  '1832': sellBuyOrBuySell,
  '1834': sellBuyOrBuySell,
  '1837SX': sellBuyOrBuySell,
  '1850': sellBuyOrBuySell,
  '1856': sellBuyOrBuySell,
  '1857': sellBuyOrBuySell,
  '1859': sellBuyOrBuySell,
  '1868': sellBuyOrBuySell,
  '1869 The Golden Spike': sellBuyOrBuySell,
  '1870': sellBuyOrBuySell,
  '1879': sellBuyOrBuySell,
  '1889': sellBuyOrBuySell,
  '1891': sellBuyOrBuySell,
  '18??': sellBuyOrBuySell,
  '18C2C': sellBuyOrBuySell,
  '18Dixie': sellBuyOrBuySell,
  '18EC': sellBuyOrBuySell,
  '18EZ Level 1': 'Not applicable (no share dealing).',
  '18EZ Level 2': sellBuyOrBuySell,
  '18EZ Level 3': sellBuyOrBuySell,
  '18GA': sellBuyOrBuySell,
  '18GM': sellBuyOrBuySell,
  '18Kaas': sellBuyOrBuySell,
  '18Mex': sellBuyOrBuySell,
  '18MS': sellBuyOrBuySell,
  '18NK': sellBuyOrBuySell,
  '18NL': sellBuyOrBuySell,
  '18NY': sellBuyOrBuySell,
  '18SY': sellBuyOrBuySell,
  '18TN': sellBuyOrBuySell,
  '1837': "Paul Work's translation of the German rules reads '.. a player may buy one certificate and may sell as many shares as desired. Either or both actions may be carried out in any order.' Interpretations of this differ. Stuart Dagger's translation reads '.. They may buy or sell during their turn in whichever order they please.",
  '1876v2': 'Sell then buy, or buy then sell but no "panic selling".',
  '18Africa': 'Sell in the first stock turn only, then buy in that and subsequent turns.',
  '18CLE': 'No. A player may carry out the sell, buy, or Corporation Starting steps in any order, but may not perform the same step twice in a single stock round turn.',
  'Crisis': 'No (i.e. sell-buy-sell). Moreover, a company may not both buy and sell shares in the same company in the same round.',
  'Rolling Stock': 'Sell or buy.',
};
