// 2.6 - What are the player certificate limits for shares in one company?

const sixtyPercent = '60%';
const seventyPercent = '70%';
const style1822 = 'Normally 60%. This can be exceeded, up to 100%, due to Minor Companies taken over by Public Companies.';
const style1817 = '100% for 2-share companies, 60% for 5-share and 10-share companies.';
const none = 'None.';
const priceProtection = "60%; may be exceeded by 'price protection'. Shares in orange and brown zones do not count towards this.";
const style18eu = '60%. This may be exceeded by minor company exchange but the excess must then be sold at the next opportunity.';
const style1841 = "60%. This applies to the total number of shares under each player's control. It may be exceeded by transfers of control but the excess must then be sold at the next opportunity.";
const brownZone = 'Shares in the brown zone do not count towards this.';

export default {
  '1761': sixtyPercent,
  '1826': sixtyPercent,
  '1827Jr': sixtyPercent,
  '1834': sixtyPercent,
  '1837SX': sixtyPercent,
  '1846': sixtyPercent,
  '1849': sixtyPercent,
  '1851': sixtyPercent,
  '1857': sixtyPercent,
  '1859': sixtyPercent,
  '1861': sixtyPercent,
  '1867': sixtyPercent,
  '1868': sixtyPercent,
  '1879': sixtyPercent,
  '1881': sixtyPercent,
  '1893': sixtyPercent,
  '18CLE': sixtyPercent,
  '18EC': sixtyPercent,
  '18EZ Level 2': sixtyPercent,
  '18EZ Level 3': sixtyPercent,
  '18FL': sixtyPercent,
  '18GA': sixtyPercent,
  '18GL': sixtyPercent,
  '18Kaas': sixtyPercent,
  '18Mex': sixtyPercent,
  '18NL': sixtyPercent,
  '18NW': sixtyPercent,
  '18SA': sixtyPercent,
  '18Scan': sixtyPercent,
  '18SY': `G variant: ${sixtyPercent}, O variant: ${none}`,
  '18TN': sixtyPercent,
  '18VA': sixtyPercent,
  '2038': sixtyPercent,
  'Steam Over Holland': sixtyPercent,
  '1800': seventyPercent,
  '18MS': seventyPercent,
  '1812': style1822,
  '1822': style1822,
  '1822CA': style1822,
  '1817': style1817,
  '18USA': style1817,
  '1824': 'Normally 60%. This can be exceeded, up to 100%, due to exchanges with Mountain Railways or Coal Railways.',
  '1825': none,
  '1829': none,
  '1829 Mainline': none,
  '1830 Cardgame': none,
  '1830BC': none,
  '1835': none,
  '1838 Rheinland': none,
  '1847': none,
  '1847AE': none,
  '1860': none,
  '1862EA': none,
  '1869 USA West': none,
  '1873': none,
  '1880': none,
  '1895': none,
  '18Africa': none,
  '18C2C': none,
  '18Rhl': none,
  '18Ruhr': none,
  '18SS': none,
  'Poseidon': none,
  'Railroad Barons': none,
  'Rolling Stock': none,
  '1830': '5 certificates. Shares in the orange and brown zones do not count towards this. Note that if you play the Reading variant you may hold 70% of the Reading.',
  '1831': 'None, unless Government intervention is in play, then 70%.',
  '1832': priceProtection,
  '1850': priceProtection,
  '1870': priceProtection,
  '18??': priceProtection,
  '18GM': priceProtection,
  '18MW': priceProtection,
  '1837': style18eu,
  '18EU': style18eu,
  '1841': style1841,
  '1898': style1841,
  '1842': '60%. Shares in the marked zone of the stock market do not count towards this.',
  '1844': 'None. But once the player has more than 50% of a company, he may not buy its shares from the initial offering.',
  '1848': 'In a 3-player game, 70%. In a 4-, 5- or 6-player game, 60%.',
  '1853': '3 or 4 players, 60%; 5 players, 50%; 6 players, 40%. Shares worth 40 or less do not count towards this.',
  '1854': '5 certificates.',
  '1856': brownZone,
  '1889': brownZone,
  '1891': brownZone,
  '1858': 'Normally 60%, but can be exceeded in the Final Exchange Round, with no requirement to sell back down.',
  '1862': '70% if there are 3 or 4 solvent players, and 60% if there are 5 or more solvent players. Thus if a company redeems half its shares one player may be able to own all that is left of it.',
  '1865 Sardinia': 'Players, 60%, Dragons (foreign investors) 50%.',
  '1869 The Golden Spike': '60%, including the option of one share purchased on a 50% margin. Additional growth shares may be purchased from the bank pool, but dividends go to the company treasury rather than the owning player.',
  '18Ardennes': '60% when bought from the initial offering. This can rise to 100% for purchases from the bank pool and Minor Company exchanges.',
  '18BL': '60%, or 70% if a payer already owns 60% and buys a further share from the initial offering.',
  '18CZ': 'Standard game: 60% of a medium or large company, 75% of a small company. Bohemia and Moravia-Silesia Variants: 70% of a large company.',
  '18Dixie': '60% excluding preferred shares. It is possible to hold up to 80% of some companies (90% of the L&N) by owning all preferred shares in addition to the regular allowance.',
  '18EZ Level 1': 'Not Applicable (no share dealing).',
  '18GB': '60% when bought from the initial offering. Purchases from the bank pool or for shares in the orange zone do not count towards this. When ten-share companies are formed, five shares will be in the bank pool and so will not count towards this limit.',
  '18Ireland': '60% for 5-share companies, 70% for 10-share companies.',
  '18Neb': '60%. As an optional rule in the two-player game only, players may allow up to 70% ownership in each ten-share company.',
  '18NK': "60%; may be exceeded by 'price protection'.",
  '18NY': '60%. This may be exceeded when buying shares from the bank pool.',
  '18OE': 'None, but for major and national companies, a player who owns 60% may only gain more by merging a minor or buying from the bank pool at twice the current share value.',
  '18PA': '60%, raised by one certificate for each local company acquired by a public company. It is possible for this variable limit to be exceeded during the conversion and acquisition steps of an OR. If this happens the player must sell certificates at the start of the next SR to comply with the current limit.',
  '18US': 'For 4-share and 5-share companies, up to 3 shares, for 10-share companies, up to 5 shares, for systems, all 10 shares.',
  '18West': "60%; may be exceeded by 'acquisition'.",
  'Crisis': '50% for type I companies, 60% for type II companies. Shares in the blue and grey zones do not count towards this.',
};
